### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by cygnet3** [cygnet3/rust-silentpayments#29]
Add some license stuff, probably MIT

**Comment by cygnet3** [comment]
> Do you think that adding a license that tells the user that fork this work to contribute back with the code changes?
> 
> In this way, it helps to grow a single library and not fragment it.
> 
> The Linux kernel use this kind of License

That sounds interesting, linux kernel uses GPLv2 right?

I was thinking MIT license because I see a lot of other projects using it (e.g. nakamoto, or the rust bech32 library).

I don't know a lot about licenses. If you think GPL is good then that might also be an interesting choice. I think there's also a difference between GPLv2 and GPLv3, not sure which would be better.

**Comment by vincenzopalazzo** [comment]
>That sounds interesting, linux kernel uses GPLv2 right?

Yes this is the one

>I don't know a lot about licenses. If you think GPL is good then that might also be an interesting choice. I think there's also a difference between GPLv2 and GPLv3, not sure which would be better.

In my view GPLv2 is good and GPLv3 is bad because restricts some usage, and GPLv2 tell you just to contribute back with the changes.

But the license is really up to you as you are the creator of this project, personally I am a little bit strict with people that do not contribute back with changes to my project in order to help grow, but again this is just my idea and your can be different

**Comment by cygnet3** [comment]
Decided to go for the MIT license after all, since it's quite popular and I'm more confident in knowing the implications of this license.
